version: '3.9'

services:
  webserver:
    image: nginx
    container_name: webserver
    ports:
      - "81:80"
    volumes:
      - ./nginx:/usr/share/nginx/html:ro

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
    volumes:
      - ./sonarr:/config
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
    volumes:
      - ./radarr:/config
    ports:
      - "7878:7878"
    restart: unless-stopped
