---
# tasks file for webserver
 - name: Include deploy for Debian systems
   include: http_deb.yaml
   when: ansible_os_family == 'Debian'

 - name: Include deploy for RedHat systems
   include: http_rh.yaml
   when: ansible_os_family == 'RedHat'

 - name: Create index.html
   include: cr_index.yaml

 - name: Setup virtual hosts
   include: cr_vhosts.yaml

 - name: Check connection to Localhost
   wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 3
   register: out

 - name: print out
   debug:
    msg: "{{ out }}"

   # - name: Check content
   #   include: check_content.yaml 

 - name: Check content to the sites
   uri:
    url: "http://{{ item.name }}"
    return_content: yes
   loop: "{{ virtual_hosts }}"
   register: this
   failed_when: "'H1' not in this.content"
   tags:
   - test

 - name: print out
   debug:
     msg: "{{ this }}"
   tags:
   - test
 
