- hosts: "{{ group }}"
  tasks:
  - name: Print variable
    debug:
      msg: "You requested user {{ user_to_add }}"
  - name: Creating user {{ user_to_add }}
    user:
      name: "{{ user_to_add }}"
      comment: Managed by ansible
      state: present
  - name: Check
    shell: |
      grep "{{ user_to_add }}" /etc/passwd
      date
    register: out
  - name: "Added authorized keys"
    authorized_key:
      user: "{{ user_to_add }}"
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - name: "Allowed user {{ user_to_add }} to sudo sudo:nopasswd in CentOS"
    when: ansible_distribution == 'CentOS'
    lineinfile:
      dest: "/etc/sudoers"
      state: "present"
      regexp: "{{ user_to_add }}"
      line: "{{ user_to_add }}  ALL=(ALL) NOPASSWD: /usr/bin/yum"
  - name: "Allowed user {{ user_to_add }} to sudo:nopasswd in Ubuntu"
    when: ansible_distribution == 'Ubuntu'
    lineinfile:
      dest: "/etc/sudoers"
      state: "present"
      regexp: "{{ user_to_add }}"
      line: "{{ user_to_add }}  ALL=(ALL) NOPASSWD: /usr/bin/apt"
  - name: "Check sudoers"
    shell: |
      grep "{{ user_to_add }}" /etc/sudoers
      date
    register: out
  - debug:
      msg: "{{ out.stdout_lines }}"
  - name: "user {{ user_to_add }} upgrade Ubuntu"
    when: ansible_distribution == 'Ubuntu'
    shell: |
      apt upgrade -y
    register: ubuntu
  - debug:
      msg: "{{ ubuntu }}"
  - name: "user {{ user_to_add }} upgrade CentOS"
    when: ansible_distribution == 'CentOS'
    shell: |
      yum upgrade -y
    register: centos
  - debug:
      msg: "{{ centos }}"
