---
- name: Nginx. Install packages
  yum:
    name: "{{ yum_nginx_packages }}"
    state: latest
    update_cache: yes

- name: Nginx. Enable and start service
  service:
    name: nginx
    state: started
    enabled: yes
