- name: nginx. install packages
  apt:
    name: "{{ nginx_packages }}"
    state: present
    update_cache: yes
- name: nginx. enable and starting
  service:
    name: nginx
    state: started
    enabled: yes    
