---
- name: Checking NOPASSWD in Sudoers
  command: "true"
  become: yes
  become_method: sudo
  changed_when: false

- name: Checking Debian/CentOS repositories
  uri:
    url: "{{ item }}"
    return_content: yes
    status_code: 200
    validate_certs: no
  loop: "{{ repositories }}"


- name: Checking Docker Hub
  uri: 
    url: "{{ docker_hub_url }}"
    return_content: yes 
  register: response
  failed_when: "'<div id=\"app\"></div>' not in response.content"

- name: Checking free space in storage
  assert:
    that: item.size_available > item.size_total|float * 0.2
    msg: "disk space has reached 80% threshold"
  with_items: '{{ ansible_mounts }}'
  ignore_errors: yes

- name: Checking free memory
  assert:
    that: ansible_memory_mb.real.free > ansible_memory_mb.real.total|float * 0.25
    msg: "Memory using has reached 75% threshold"
  ignore_errors: yes

