apt_http_packages:
  - nginx
  


red_http_packages:
  - nginx
  - libsemanage-python
  - libselinux-python
 
default_home: "{{ '/var/www/html' if (ansible_os_family == 'Debian') else '/usr/share/nginx/html' }}"

site_deb: "local-deb.site"
site_red: "local-cent.site"

virtual_hosts:  
  - { name: "{{ site_red }}", ip: "{{ hostvars[\"host9\"].ansible_host }}"}
  - { name: "{{ site_deb }}", ip: "{{ hostvars[\"host10\"].ansible_host }}"}


