ec_all:
  vars: 
    ansible_ssh_user: root
  children:
    workshop-hosts:
      hosts:
        work_shop_01:
          ansible_host: 192.168.201.1
jump:
  hosts:
    ec_jump:
      ansible_host: 178.124.206.53
