- hosts: workshop_01
  pre_tasks:

  - debug:
      msg: "{{ ansible_host }}"

  - name: Install packages
    apt:
      name: "{{ apt_redmine_packages }}"
      state: latest
      update_cache: yes

  roles:
    - rm
    - mysql

  tasks:      
  - name: "Add {{ app_fqdn }} to host file"
    shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
    tags: 
      - test

  - name: Check deploy  
    block:    
      - uri:    
          url: "http://{{ app_fqdn }}"
          return_content: yes
        register: this
        failed_when: "'Jean-Philippe Lang' not in this.content"        
    rescue:
      - name: Send notification
        debug:
          msg: "{{ app_fqdn }} deploy failed"
    tags:
      - test        

  - lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127.0.0.1       {{ app_fqdn }}'
    tags:
      - test
      - always

      
