root@9b1516a5e6c8:/etc/ansible# ansible-playbook 1st_playbook.yaml -i inv.yaml

PLAY [all_work_hosts] ********************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [host12]
ok: [host11]

TASK [Print OS information] **************************************************************************************************************************************************************************************
ok: [host11] => {
    "msg": "OSNAme: CentOS, OSVersion: 7.9"
}
ok: [host12] => {
    "msg": "OSNAme: Ubuntu, OSVersion: 18.04"
}

TASK [Print Mount information] ***********************************************************************************************************************************************************************************
ok: [host11] => {
    "msg": "Mount: /, Volume: 21003583488, Used: 1850187776"
}
ok: [host12] => {
    "msg": "Mount: /, Volume: 21003583488, Used: 2166575104"
}

TASK [Print RAM information] *************************************************************************************************************************************************************************************
ok: [host11] => {
    "msg": "RAM: 4096, FREE_RAM: 3564"
}
ok: [host12] => {
    "msg": "RAM: 4096, FREE_RAM: 3962"
}

PLAY RECAP *******************************************************************************************************************************************************************************************************
host11                     : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
host12                     : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
