- name: Install Jenkins with Nginx
  hosts: work_shop
  gather_facts: false
  become: yes
  become_user: root
  remote_user: root 
  vars:
    - update_apt_cache: yes
  pre_tasks:
  - debug:
      msg: "{{ ansible_host }}"
  - name: Output hostname
    shell: hostname
    register: hostname
  - debug:
      msg: "{{ hostname.stdout }}"
  roles:
    - jenkins
    - nginx
    tasks:
  - name: "Add {{ app_fqdn }} to host file"
    shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
    tags: 
      - test
  - uri:
      url: "http://{{ app_fqdn }}"
      return_content: yes
    register: this
    failed_when: "'g' not in this.content"
    tags: 
      - test
  - lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127.0.0.1       {{ app_fqdn }}'
    tags: 
      - test
      - always
  - name: Test
    uri:
      url: "http://localhost"
      return_content: yes
    register: out_uri
  - name: Print output
    debug:
      msg: "Status: {{ out_uri.status }}"
