---
nginx_conf_dir: "/etc/nginx/conf.d/"

# debian
debian_virtual_hosts:
  - "local-debian1.site"
  - "local-debian2.site"

debian_nginx_html_dir: "/var/www/"

#centos
centos_virtual_hosts:
  - "local-centos1.site"
  - "local-centos2.site"

centos_nginx_html_dir: "/usr/share/nginx/html/"
