- hosts: redmine
  vars_files: vars/redmine_vars.yaml

  pre_tasks:
  - debug:
      msg: "{{ ansible_host }}"

  roles:
    - mysql
    - redmine

  tasks:

    - name: "Add {{ app_fqdn }} to host file"
      shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
      tags:
        - test

    - name: Check Deploy Redmine
      block:
        - name: Check content
          uri:
            url: "http://{{ app_fqdn }}"
            return_content: yes
          register: this
          failed_when: "'Jean-Philippe Lang' not in this.content"
          tags:
            - test
        - name: Send notification
          slack:
            token: "{{ slack_token }}"
            msg: 'Deploy Redmine on {{ ansible_ssh_host }}: OK'
            channel: '#notifications_volkov'
            username: 'Ansible sender'
            parse: 'full'
          tags:
            - test
      rescue:
        - name: Send notification
          slack:
            token: "{{ slack_token }}"
            msg: 'Deploy Redmine on {{ ansible_hostname }}: Failed''
            channel: '#notifications_volkov'
            username: 'Ansible sender'
            parse: 'full'
          tags:
            - test

    - name: "Remove {{ app_fqdn }} from host file"
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '^127.0.0.1       {{ app_fqdn }}'
      tags:
        - test
        - always
