- hosts: redmine
  pre_tasks:
  - name: "Show ansible host"
    debug:
      msg: "{{ ansible_host }}"
  
  roles:
    - mysql 
    - redmine

  tasks:
  - name: "add redmine to host file"
    shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
    tags: 
      - test
  
  - name: "Connctivity Test" 
    block:
      - uri:
          url: "http://{{ app_fqdn }}"
          return_content: yes
        register: this
        failed_when: "'Jean-Philippe Lang' not in this.content"
        tags: 
        - test
    rescue:
        - name: Send notification
          slack:
            token: TFBPBNB2L/B032H94UQF2/6BtwlWn4l3XOrtdYLya7Mfjv
            msg: 'Test Redmine Page - failed'
            channel: '#my_ansible_channel'
            username: 'Ansible sender#' 
            icon_url: https://agardner.net/wp-content/uploads/2018/08/ansible-logo.png
            parse: 'full'

  - lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127.0.0.1       {{ app_fqdn }}'
    tags: 
      - test
      - always