- hosts: work_shop
  pre_tasks:
  - debug:
      msg: "{{ ansible_host }}"

  - name: Output hostname
    shell: hostname
    register: hostname
  - debug:
      msg: "{{ hostname.stdout }}"

  roles:
    - mysql
    - redmine_app

  tasks:
  - name: "Add {{ app_fqdn }} to host file"
    shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
    tags:
      - test
  
  - uri:
      url: "http://{{ app_fqdn }}"
      return_content: yes
    register: this
    failed_when: "'Jean-Philippe Lang' not in this.content"
    tags: 
      - test

  - lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127.0.0.1       {{ app_fqdn }}'
    tags: 
      - test
      - always
