---
- name: Install Nginx on Debian Family
  apt:
    name: nginx
    state: latest
  become: yes

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
  
- name: Create virtual domain directory
  file:
    path: "/var/www/{{ item }}"
    state: directory
  loop: "{{ virtual_domain }}"
  become: yes
  
- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
  
- name: Create index.html for every virtual domain
  template:
    src: index.html.j2
    dest: "/var/www/{{ item }}/index.html"
  loop: "{{ virtual_domain }}"
  become: yes
  notify: restart_nginx
  
- name: Create config file for every virtual domain
  template:
    src: config.conf.j2
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
  loop: "{{ virtual_domain }}"
  become: yes
  notify: restart_nginx
  
- name: Create links
  file: 
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    state: link
  loop: "{{ virtual_domain }}"
  become: yes
  notify: restart_nginx
