version: '3.3'

services:
  webserver_01:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver01
    ports:
      - "8080:80"
    restart: always    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    restart: unless-stopped        
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - 7878:7878
    restart: unless-stopped        
