
---
- name: hosts_information
  hosts: all_workers
  tasks: 
    - name: OS
      debug:
        msg:
          - "Name = {{ ansible_distribution }}"
          - "Version = {{ ansible_distribution_version }}"
    - name: Mounts
      debug:
        msg: 
          - "Mount point = {{ item.mount }}"
          - "Capacity = {{ (item.size_total/1048576)|int }}MB"
          - "Used = {{ ((item.size_total-item.size_available)/1048576)|int }}MB"
      when: item.mount == '/'
      with_items:
        - "{{ ansible_mounts }}"
    - name: RAM
      debug:
        msg: 
          - "Total = {{ ansible_memtotal_mb }}MB"
          - "Free = {{ ansible_memfree_mb }}MB"