---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.19.0
        args:
          - "--config.file=/etc/alertmanager/config.yml"
          - "--storage.path=/alertmanager"
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: alertmanager
        emptyDir: {}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global: {}
    route:
      receiver: slack_alarm
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 1m 
    receivers:
    - name: slack_alarm
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#aalarm'
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '9093'
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager-ingres
  namespace: monitoring
spec:
  rules:
  - host: alert.k8s-19.sa
    http:
      paths:
      - path: /
        backend:
          serviceName: alertmanager
          servicePort: 9093
