- hosts: all_workers
  gather_facts: true
  pre_tasks:
  - name: "Show ansible host"
    debug:
      msg: "OS Version = {{ ansible_distribution }}  {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
  
  roles:
    - test