---
nginx_config: etc/nginx/conf.d/

default_home: "{{ '/var/www/html' if (ansible_os_family == 'Debian') else '/usr/share/nginx/html' }}"

site_deb: "local-deb.site"
site_cent: "local-cent.site"

virtual_hosts:
  - { name: "{{ site_cent }}", ip: "{{ hostvars[\"work_01\"].ansible_host }}"}
  - { name: "{{ site_deb }}", ip: "{{ hostvars[\"work_02\"].ansible_host }}"}
