--- 

- hosts: redmine
  
  vars: 
     app_fqdn: redmine-27.sa
     apt_redmine_packages: 
       - git
       - ruby-full
       - build-essential
       - libmysqlclient-dev
       - imagemagick
       - libmagickwand-dev
       - apache2
       - libapache2-mod-passenger
       - mysql-server
       - mysql-client
       - python3-pymysql
       - python3-mysqldb
       - python-pymysql
       - python-mysqldb
  
  pre_tasks: 
    - debug: 
        msg: "{{ ansible_host }}"
        
    - apt: 
        name: "{{ apt_redmine_packages }}"
        state: latest
        update_cache: true
      name: "Redmine. Install packages"
  
  
  roles: 
    - redmine
    - mysql
  
  post_tasks: 
    - name: "Add {{ app_fqdn }} to host file"
      shell: "echo \"127.0.0.1       {{ app_fqdn }}\" >> /etc/hosts"
      tags: 
        - test
        
    - name: "Test deployment"
      tags: test
      vars:
#Hide slack channel secreet
        slack_token: !vault |
               $ANSIBLE_VAULT;1.1;AES256
               63303236346138343536313066383130633138303331633134323830616531623562353431633964
               3863623936306430393866343763653236373462343831650a303361656130663638343462376461
               33376263353238363665633736393630333962643137643530373465356265366238653037663036
               3431616135653039630a643561613566653062343430373631363164306235366236333334393136
               39353636613434383732353764323062336264646131316366323239343562333731653236663063
               3938376431343031386638316531643635653364316330663666
        
      block:
        - name: "==== Test deployment ===="
          uri:
            url: "http://{{ app_fqdn }}"
            return_content: yes
          register: this
          failed_when: "'Jean-Philippe Lang' not in this.content"
          
        - name: Send successfull notification to slack
          slack:
             token: "{{slack_token}}"
             msg: 'Test deployment successfull'
             channel: '#sa_academy_deployments'
             username: 'Ansible bot#' 
             parse: 'full'                 
      rescue:
         - name: Send failure notification to slack
           slack:
             token: "{{slack_token}}"
             msg: 'Deployment failed!!!'
             channel: '#sa_academy_deployments'
             username: 'Ansible bot#' 
             parse: 'full'
    
        
    - uri: 
        return_content: true
        url: "http://{{ app_fqdn }}"
        
    - lineinfile: 
        path: /etc/hosts
        regexp: "^127.0.0.1       {{ app_fqdn }}"
        state: absent
      tags: 
        - test
        - always
